### ISSUE TITLE
Can't load FBX files

### ISSUE THREAD

**Issue by dragosdydy** [Itee/threejs-full-es6#6]
Hello,
I am trying to load some FBX files in a React component and I can't do it. No errors show in the console. I noticed that FBXLoader needs zlib library, and i have installed it from npm `npm install zlipjs` - but what after that? The documentation of that package is not too helpful too.
I have tried OBJ files and it works just fine.
Could you please give me a hand on this ?

Thank you for your work on this project!

**Comment by Itee** [comment]
You're welcome ! 

I will take a look on this.

**Comment by Itee** [comment]
Ok it is a three bug ! See [https://github.com/mrdoob/three.js/issues/12924](https://github.com/mrdoob/three.js/issues/12924) and [https://github.com/mrdoob/three.js/pull/12929](https://github.com/mrdoob/three.js/pull/12929)

That come from `LoaderUtils.decodeText` that receive a basic array instead of an ArrayBuffer or ArrayBufferView !

The r90 release should be done this week. It will be fixed soon, so be patient the fix is coming !

About 

> The documentation of that package is not too helpful too.

What could be improved ?

Best regards

**Comment by dragosdydy** [comment]
Oh, thanks then! I will wait for the release and hope the issue will be fixed. 

> What could be improved ?

I was not talking about your repo, but about the `zlibjs` one 👍 

Thank you!

**Comment by Itee** [comment]
Ok ! 

So i close
