### ISSUE TITLE
Could not find a declaration file for module 'threejs-full-es6'

### ISSUE THREAD

**Issue by ranbuch** [Itee/threejs-full-es6#7]
```
import { Scene, GLTFExporter, GLTFLoader, OrbitControls, PerspectiveCamera, Color, AmbientLight, DirectionalLight, SpotLight, WebGLRenderer, PCFSoftShadowMap } from 'threejs-full-es6';
import { Utils } from './utils';
```

The `from 'threejs-full-es6'` has this error:

```Could not find a declaration file for module 'threejs-full-es6'. 'c:/Users/ranbu/Documents/dev/threejs-viewer/node_modules/threejs-full-es6/builds/Three.es.js' implicitly has an 'any' type.
  Try `npm install @types/threejs-full-es6` if it exists or add a new declaration (.d.ts) file containing `declare module 'threejs-full-es6';`
```

And when I'm trying to build it:
`
TypeScript error: src/index.ts(1,166): Error TS7016: Could not find a declaration file for module 'threejs-full-es6'. 'c:/users/ranbu/documents/dev/threejs-viewer/node_modules/threejs-full-es6/builds/Three.es.js' implicitly has an 'any' type.
  Try `npm install @types/threejs-full-es6` if it exists or add a new declaration (.d.ts) file containing `declare module 'threejs-full-es6';`
`

Any idea on what's wrong?

If its not a bug - Maybe you can provide some simple example or a boilerplate for how to use and build a project that is using this module?

Thank you.

**Comment by Itee** [comment]
It look like that a TypeScript definition is missing.
But this project is not under TypeScript so... 

Are you trying to build it using TypeScript ?

The `@types/threejs-full-es6` does not exist at all, and won't exist in near future.

The error message is clear. If  `@types/threejs-full-es6` don't exist you should create a file with extension .d.ts containing `declare module 'threejs-full-es6';`

May be this will do the trick and fix you issue ?

Finally, if you're trying to import it in a node environment maybe you should look inside the `node_module/threejs-full-es6/builds` folder and use one of the other build. Because the `import { Foo } from 'threejs-full-es6' ` is mapped to Three.es.js build file.

Best regards

**Comment by Itee** [comment]
/ping @ranbuch 
Still an issue ?

**Comment by ranbuch** [comment]
@Itee no, Thank you.
